CREATE DATABASE IF NOT EXISTS `todoSystem` COLLATE = UTF8_GENERAL_CI;

-- tables 

CREATE TABLE IF NOT EXISTS `todoSystem`.`users` (
    `id` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `email` VARCHAR(25) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `admin` TINYINT(1) DEFAULT 0
)  ENGINE=MYISAM DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `todoSystem`.`tasks` (
    `id` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(25) NOT NULL,
    `content` TEXT(5000) NOT NULL,
    `finished` VARCHAR(255) DEFAULT 'none',
    `created` TIMESTAMP,
    `creator` VARCHAR(25)
)  ENGINE=MYISAM DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
